### PR TITLE
support Python3

### PR DESCRIPTION
**Pull request by Wenzel**
DO NOT MERGE YET

This is on ongoing work to get `Rekall` with `Python3` compatibility.

We agreed that this is a necessary work for the long term.
-> #66

I open this PR to get some feedback and comments about the way we should proceed,
as i'm not familiar porting python2 projects to python3, just learning.

The Rekall command line is not working, i'm blocked by the `capstone`.import which fails to load the library.
-> https://github.com/aquynh/capstone/issues/961

Here is a script if you want to reproduce the current state of my work:
https://gist.github.com/Wenzel/5185887c3f230fedc7605c645c08dc71

Thanks !

### CODE REVIEW

**Comment by Wenzel** [comment]
Status update:

I solved some dependency issues, and i have the rekall shell interface loaded.

However, as soon as i run a plugin, i have errors.
To be fixed.

The script has been updated, if anyone wants to reproduce the current state:
https://gist.github.com/Wenzel/5185887c3f230fedc7605c645c08dc71

Thanks @scudette

**Comment by Wenzel** [comment]
New fixes and a new bug, if anyone knows why this exception is raised:
**AttributeError: 'MemoryDataStore' object has no attribute 'QueryPredicate'**

~~~
Traceback (most recent call last):
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-lib/rekall_lib/utils.py", line 1020, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/session.py", line 1060, in profile
    res = self.GetParameter("profile_obj")
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/session.py", line 766, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/session.py", line 801, in _RunParameterHook
    result = hook.calculate()
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugins/guess_profile.py", line 726, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-lib/rekall_lib/registry.py", line 74, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugins/addrspaces/aff4.py", line 142, in __init__
    self._AutoLoadAFF4Volume(volume_path)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugins/addrspaces/aff4.py", line 208, in _AutoLoadAFF4Volume
    for (subject, _, value) in self.resolver.QueryPredicate(
AttributeError: 'MemoryDataStore' object has no attribute 'QueryPredicate'
~~~

**Comment by scudette** [comment]
Oh yeah I noticed that one. This method was removed when the new AFF4 implementation was submitted. Just put it back.

https://github.com/google/aff4/commit/6b4e143afc5850831537b9fe529c98f1478eada5#diff-3eee79b0e104f799067ab87017510e43L338

**Comment by Wenzel** [comment]
I fixed a couple of issues due to string manipulation, and i converted them to bytes.

Now i have an issue here:
**TypeError: Argument 'data' has incorrect type (expected str, got bytes)**
~~~
Traceback (most recent call last):
  File "/home/tarrma/Bureau/rekall3_test/venv/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/rekal.py", line 97, in main
    user_session=user_session)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/args.py", line 431, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugin.py", line 961, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugin.py", line 427, in is_active
    profile = (session.profile != None and
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-lib/rekall_lib/utils.py", line 1020, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/session.py", line 1060, in profile
    res = self.GetParameter("profile_obj")
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/session.py", line 766, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/session.py", line 801, in _RunParameterHook
    result = hook.calculate()
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugins/guess_profile.py", line 757, in calculate
    profile_obj = self.ScanProfiles()
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugins/guess_profile.py", line 625, in ScanProfiles
    return self._ScanProfiles()
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/plugins/guess_profile.py", line 678, in _ScanProfiles
    for offset, hit in scanner.scan(maxlen=autodetect_scan_length):
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/scan.py", line 476, in scan
    res = self.check_addr(scan_offset, buffer_as=buffer_as)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/scan.py", line 560, in check_addr
    val = self.check.check(buffer_as, offset)
  File "/home/tarrma/Bureau/rekall3_test/rekall/rekall-core/rekall/scan.py", line 124, in check
    self.hits = sorted(self.engine.findall(buffer_as.data),
TypeError: Argument 'data' has incorrect type (expected str, got bytes)
~~~
This is because data is now `bytes` instead of a `string`.
We want to manipulate the address space using `bytes`, that's why i made these fixes:
https://github.com/google/rekall/pull/272/commits/c4b23102d92cb7f60e371d6a233a884ded02ec33
https://github.com/google/rekall/pull/272/commits/fb28db8040da0a02991b78a16358fcaea017510a
Is it right ?

How should we fix this ?

**Comment by Wenzel** [comment]
cc @scudette

**Comment by scudette** [comment]
Thanks for this PR. It was quite a bit more complicated than I thought :-).

I am closing this because the current release fully supports python 3. Please file an issue if there are any problems left over. Thanks again for your efforts @Wenzel.

**Pull request closed without merging**
