### PR TITLE
add VMIAddressSpace

### PR DESCRIPTION
**Pull request by Wenzel**
This PR adds support for a new address space based on virtual machine introspection, and built on top of the [LibVMI](https://github.com/libvmi/libvmi) library.

It uses libvmi's API to read and write the physical memory of a `domain` running under Xen or KVM.

Example under a KVM domain named `nitro_win7x64`:
~~~
$ rekall -f vmi://nitro_win7x64 pslist 
xc: error: Could not obtain handle on privileged command interface (2 = No such file or directory): Internal error
VMI_ERROR: Failed to open libxc interface.
  _EPROCESS            name          pid   ppid  thread_count handle_count session_id wow64    process_create_time       process_exit_time    
-------------- -------------------- ----- ------ ------------ ------------ ---------- ------ ------------------------ ------------------------
0xfa8001108890 System                   4      0           75          437          - False  2018-03-03 07:38:16Z     -                       
0xfa800217a350 smss.exe               248      4            4           29          - False  2018-03-03 07:38:16Z     -                       
0xfa8002d41b30 svchost.exe            312    464           21          413          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002969330 csrss.exe              320    312            8          332          0 False  2018-03-03 07:38:17Z     -                       
0xfa80029897c0 wininit.exe            368    312            7           89          0 False  2018-03-03 07:38:17Z     -                       
0xfa80029858f0 csrss.exe              380    360            7          150          1 False  2018-03-03 07:38:17Z     -                       
0xfa8002ad8b30 winlogon.exe           420    360            6          117          1 False  2018-03-03 07:38:17Z     -                       
0xfa80022294a0 services.exe           464    368           17          204          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002b16b30 lsass.exe              472    368            9          473          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002b1bb30 lsm.exe                480    368           10          146          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002b6ea90 svchost.exe            584    464           15          348          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002b92b30 svchost.exe            648    464            9          217          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002bb3a30 svchost.exe            700    464           19          391          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002bbdb30 svchost.exe            776    464           24          437          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002cf8890 svchost.exe            864    464           42          741          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002d065f0 audiodg.exe            928    700            6          120          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002d349e0 svchost.exe           1004    464           15          286          0 False  2018-03-03 07:38:18Z     -                       
0xfa8002dc33a0 dwm.exe               1072    776            5           70          1 False  2018-03-03 07:38:19Z     -                       
0xfa8002dc8b30 explorer.exe          1084   1064           32          640          1 False  2018-03-03 07:38:19Z     -                       
0xfa8002e04460 spoolsv.exe           1148    464            6           76          0 False  2018-03-03 07:38:19Z     -                       
0xfa8002e16420 taskhost.exe          1184    464            9          152          1 False  2018-03-03 07:38:19Z     -                       
0xfa8002e27430 svchost.exe           1208    464           25          325          0 False  2018-03-03 07:38:19Z     -                       
0xfa8002e74b30 svchost.exe           1328    464           13          168          0 False  2018-03-03 07:38:19Z     -                       
0xfa8002f32900 sppsvc.exe            1412    464            6          149          0 False  2018-03-03 07:38:20Z     -                       
0xfa8002f04b30 wlms.exe              1532    464            5           45          0 False  2018-03-03 07:38:20Z     -                       
0xfa800219d780 svchost.exe           1744    464            6           94          0 False  2018-03-03 07:38:20Z     -  
~~~

Note: This address space is based on the new python bindings for Libvmi, which are not merged upstream yet.
https://github.com/libvmi/libvmi/pull/532

Feedback is welcomed !

### CODE REVIEW

**Comment by smaresca** [comment]
The error message is potentially confusing -- a user targeting a KVM guest will not expect to see output related to the Xen LibVMI driver. 

Indicating the hypervisor target via the URI would provide a helpful hint for vmi_init and avoid the unexpected message. Some ideas for example: vmikvm://nitro_win7x64, vmixen://nitro_win7x64, or vmi://kvm/nitro_win7x64

**Comment by Wenzel** [comment]
I agree with @smaresca that the error message might be confusing.
but wow, that was fast, already merged :D

@smaresca  We still need to look at the new python bindings for libvmi and merge them ;)

**Comment by scudette** [comment]
No problems - I merged because it is unlikely to break existing
functionality and we can always improve in the future :-). An option to
changing the prefix is to add another flag for the domain but this might
clutter all the flags. Maybe we need a way to pass arbitrary things to the
session object so it could be something like:

--session_param domain=kvm

or something. I guess it all boils down to whether it makes sense to have
arbitrary domains or is it something which could be autodetected?

Thanks
Michael.

**Comment by bridgeythegeek** [comment]
All,

Just an FYI...

I created a new install of Rekall today by following the instructions in the [Quick Start](https://github.com/google/rekall/#quick-start), specifically, the instructions for cloning from github.

This went swimmingly, (well, besides having to `apt install libncurses5-dev`), but trying `rekall -h` it bailed:
```
$ rekall -h
Traceback (most recent call last):
  File "/home/btg/venv-rekall/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/btg/venv-rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/btg/venv-rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/btg/venv-rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/btg/venv-rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/btg/rekall/rekall-core/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/home/btg/venv-rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/btg/venv-rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/btg/rekall/rekall-core/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/home/btg/rekall/rekall-core/rekall/plugins/addrspaces/__init__.py", line 20, in <module>
    from rekall.plugins.addrspaces import vmi
  File "/home/btg/rekall/rekall-core/rekall/plugins/addrspaces/vmi.py", line 1, in <module>
    from libvmi import Libvmi
ImportError: No module named libvmi
```

With no obvious `pip install` or `apt install` fix, I solved it by removing [the include for the vmi address space from `.../addrspaces/__init__.py`](https://github.com/google/rekall/blob/ff4918c1b69a967ac86b7039873ac3b6da6dc237/rekall-core/rekall/plugins/addrspaces/__init__.py#L20):
```
from rekall.plugins.addrspaces import intel
from rekall.plugins.addrspaces import macho
from rekall.plugins.addrspaces import mips
from rekall.plugins.addrspaces import mmap_address_space
from rekall.plugins.addrspaces import pagefile
#from rekall.plugins.addrspaces import vmi
```

**Comment by Wenzel** [comment]
Thanks for reporting @bridgeythegeek , and i'm terribly sorry i broke your installation.
I should have catched this ImportError right away.
Actually i wasn't expecting this PR to merge that was, i thought there would have been more discussions.

But anyway, i opened a PR here: #375

**Pull request merged**
