### PR TITLE
major revision

### PR DESCRIPTION
**Pull request by vivianezw**
As requested, my revision, as a pull request. Now it's your turn. :-)
(I hope I did not forget anything.)

### CODE REVIEW

**Comment by vivianezw** [comment]
As the winpmem is probably going to move to another location (entirely), I'm going to close this pull request.
Impatient people may compile this current version in the meantime as beta-testers, as it works and has been tested, just don't forget 'bcdedit /set testsigning on'. (If you do testing, please report any bugs to Scudette.)

I would offer temporary x86/x64 winpmems, but I dislike appending precompiled binaries and it's better to wait for the final fully signed version anway.

**Comment by eltms** [comment]
Hello @vivianezw, many thanks for the updates regarding winpmem, could please I get a copy of the beta version for  x86/x64 winpmems to test? and also when is expected to bush the latest updates?
Cheers,
Elty

**Comment by vivianezw** [comment]
This is a provisoric version and for beta testers only. 

PW: betatest
[winpmem_provisoric_version.zip](https://github.com/google/rekall/files/5303977/winpmem_provisoric_version.zip)

Known issues: 
* having Hyper-V and its features enabled and using a latest Win10 VM: iospace method will fail.
* on Hyper-V, disable "dynamic memory" for VMs. This is causing Memory Range Run fragmentation. (A bug of Microsoft, actually.)
* PTE method from scudette was never written for x86 and therefore will not work on 32 bit.
* Disable memory compression (newer win 10 builds only) to help volatility. (elevated powershell: "Disable-MMAgent -mc", reboot)
* Don't use latest Win10, if you want to load it afterwards in volatility 2!
* Don't forget "bcdedit /set testsigning on" & reboot! It's testsigned only.

**Comment by eltms** [comment]
Hello @vivianezw, @scudette 
Please I was wondering if there is a way to get winpmem working without this "Don't forget "bcdedit /set testsigning on" workaround? because that requires a restart, then the Live Ram imaging will be less useful after a fresh restart.  
Thanks,
Elty

**Pull request closed without merging**
