### PR TITLE
pas2kas.py: suppress warning on apt install

### PR DESCRIPTION
**Pull request by ValZapod**
/usr/lib/python3/dist-packages/rekall/plugins/common/pas2kas.py:176: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if task is 'Kernel':

### CODE REVIEW

**Comment by ValZapod** [comment]
@googlebot I signed it!

**Comment by scudette** [comment]
I have not written any python for a while but it used to be idiomatic
python to use is with None and not ==. I think the above comment is only
talking about the comparison with a literal string "kernel". Maybe that is
the only place that needs changing?

**Comment by ValZapod** [comment]
@scudette Yeah, I just did it to be safe: `with a literal`.

**Comment by scudette** [comment]
I don't think None is a literal. I think it's a Singleton and therefore
using is is actually the correct thing.

**Comment by ValZapod** [comment]
@scudette No, only 'Kernel' is a literal. But it does not metter, is not it?

**Comment by scudette** [comment]
http://google.github.io/styleguide/pyguide.html#214-truefalse-evaluations

Always use if foo is None: (or is not None) to check for a None value-e.g.,
when testing whether a variable or argument that defaults to None was set
to some other value. The other value might be a value that’s false in a
boolean context!

**Comment by ValZapod** [comment]
@scudette Wow. Just wow. Okay, i will fix it.

**Comment by ValZapod** [comment]
@scudette Here you are!

**Pull request merged**
